name: "Terraform Apply"

on:
  # Trigger on changes to the infra pushed to main
  push:
    branches:
      - main
    paths:
      - "infra/gcp/**"

  # Also trigger manually, anytime
  workflow_dispatch:

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BOOTSTRAP_SA_KEY }}

      - name: Terraform Init
        working-directory: ./infra/gcp/environments/dev
        run: terraform init -backend-config=backend.conf

      - name: Terraform Apply
        working-directory: ./infra/gcp/environments/dev
        run: |
          terraform apply -refresh-only -auto-approve
          terraform apply -auto-approve

  terraform-prd:
    runs-on: ubuntu-latest
    environment: prod # GitHub environment, not the directory name. This adds a manual approval gate.

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BOOTSTRAP_SA_KEY }}

      - name: Terraform Init
        working-directory: ./infra/gcp/environments/prd
        run: terraform init -backend-config=backend.conf

      - name: Terraform Apply
        working-directory: ./infra/gcp/environments/prd
        run: |
          terraform apply -refresh-only -auto-approve
          terraform apply -auto-approve
