name: "Terraform Selective Destroy"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to destroy"
        required: true
        type: choice
        options:
          - dev
          - prd
      component:
        description: "The component to destroy"
        required: true
        type: choice
        options:
          - compute-only
          - everything

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BOOTSTRAP_SA_KEY }}

      - name: Destroy Compute
        if: ${{ github.event.inputs.component == 'compute-only' }}
        working-directory: ./infra/gcp/environments/${{ github.event.inputs.environment }}/compute
        run: |
          terraform init -backend-config=backend.conf
          terraform destroy -auto-approve

      - name: Destroy Everything
        if: ${{ github.event.inputs.component == 'everything' }}
        working-directory: ./infra/gcp/environments/${{ github.event.inputs.environment }}
        run: |
          cd compute
          terraform init -backend-config=backend.conf
          terraform destroy -auto-approve
          cd ../foundation
          terraform init -backend-config=backend.conf
          terraform destroy -auto-approve
