name: "Terraform Apply"

on:
  # Trigger on changes to the infra pushed to main
  push:
    branches:
      - main
    paths:
      - "infra/gcp/**"

  # Also trigger manually, anytime
  workflow_dispatch:

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BOOTSTRAP_SA_KEY }}

      - name: Apply Foundation
        working-directory: ./infra/gcp/environments/dev/foundation
        run: |
          terraform init -backend-config=backend.conf
          terraform apply -auto-approve

      - name: Apply Compute
        working-directory: ./infra/gcp/environments/dev/compute
        run: |
          terraform init -backend-config=backend.conf
          terraform apply -auto-approve

  terraform-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd # GitHub environment. This adds a manual approval gate.
      url: ${{ steps.deploy.outputs.url }}
    needs: [terraform-dev]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_BOOTSTRAP_SA_KEY }}

      - name: Apply Foundation
        working-directory: ./infra/gcp/environments/prd/foundation
        run: |
          terraform init -backend-config=backend.conf
          terraform apply -refresh-only -auto-approve
          terraform apply -auto-approve

      - name: Apply Compute
        working-directory: ./infra/gcp/environments/prd/compute
        run: |
          terraform init -backend-config=backend.conf
          terraform apply -refresh-only -auto-approve
          terraform apply -auto-approve
